# Generated by Django 5.2.7 on 2025-12-06 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_remove_supervisor_user_delete_collector_and_more'),
        ('collector', '0004_alter_collector_first_name_alter_collector_last_name'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_demand', 'On Demand')], max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='collections/photos/before/')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='collections/photos/after/')),
                ('segregation_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.collector')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route')),
            ],
        ),
    ]
