# Generated by Django 5.2.7 on 2025-12-06 15:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_supervisor_user_delete_collector_and_more'),
        ('collection_management', '0001_initial'),
        ('collector', '0004_alter_collector_first_name_alter_collector_last_name'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionrecord',
            options={'ordering': ['-collected_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='bag_count',
            field=models.IntegerField(default=0, help_text='Number of waste bags collected', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='bin_size_liters',
            field=models.IntegerField(blank=True, choices=[(120, '120 Liters'), (240, '240 Liters'), (360, '360 Liters'), (660, '660 Liters'), (1100, '1100 Liters')], help_text='Standard bin size if applicable', null=True),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='collection_end',
            field=models.DateTimeField(blank=True, help_text='When collection completed', null=True),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='collection_start',
            field=models.DateTimeField(blank=True, help_text='When collector arrived', null=True),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='estimated_volume_liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated volume in liters', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='route_stop',
            field=models.OneToOneField(blank=True, help_text='Links to specific stop in route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_record', to='routes.routestop'),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='waste_type',
            field=models.CharField(choices=[('mixed', 'Mixed Waste'), ('organic', 'Organic/Wet Waste'), ('recyclable', 'Recyclable'), ('plastic', 'Plastic'), ('e-waste', 'E-Waste'), ('bulk', 'Bulk Waste')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='client.client'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collected_at',
            field=models.DateTimeField(blank=True, help_text='Actual collection timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collection_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled Collection'), ('on_demand', 'On-Demand Collection'), ('emergency', 'Emergency Collection')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='collector.collector'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS location where collection occurred', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS location where collection occurred', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or issues', null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='photo_after',
            field=models.ImageField(blank=True, help_text='Photo after collection', null=True, upload_to='collections/photos/after/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='photo_before',
            field=models.ImageField(blank=True, help_text='Photo before collection', null=True, upload_to='collections/photos/before/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='route',
            field=models.ForeignKey(blank=True, help_text='For subscription-based scheduled collections', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='routes.route'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Scheduled collection date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='segregation_score',
            field=models.IntegerField(blank=True, help_text='Waste segregation quality (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('missed', 'Missed'), ('rejected', 'Rejected - Poor Segregation'), ('partial', 'Partial Collection'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['client', '-collected_at'], name='collection__client__011ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['collector', '-collected_at'], name='collection__collect_c12a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['route', 'status'], name='collection__route_i_384a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['scheduled_date', 'status'], name='collection__schedul_ef15ec_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['collection_type', 'status'], name='collection__collect_02143c_idx'),
        ),
    ]
