# Generated by Django 5.2.7 on 2025-12-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0002_alter_collectionrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('bank', 'Bank Transfer'), ('later', 'Invoice Later')], default='later', max_length=20),
        ),
    ]
