# Generated by Django 5.2.7 on 2025-12-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0003_collectionrecord_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionrecord',
            old_name='gps_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='collectionrecord',
            old_name='gps_longitude',
            new_name='longitude',
        ),
    ]
