# Generated by Django 5.2.7 on 2025-12-11 02:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0004_rename_gps_latitude_collectionrecord_latitude_and_more'),
        ('routes', '0009_alter_route_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='bag_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='bin_size_liters',
            field=models.IntegerField(blank=True, choices=[(120, '120L'), (240, '240L'), (360, '360L'), (660, '660L'), (1100, '1100L')], null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collection_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collection_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collection_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('on_demand', 'On-Demand'), ('emergency', 'Emergency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='estimated_volume_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='photo_after',
            field=models.ImageField(blank=True, null=True, upload_to='collections/photos/after/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='photo_before',
            field=models.ImageField(blank=True, null=True, upload_to='collections/photos/before/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='routes.route'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='route_stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_record', to='routes.routestop'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='segregation_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='waste_type',
            field=models.CharField(choices=[('mixed', 'Mixed Waste'), ('organic', 'Organic'), ('recyclable', 'Recyclable'), ('plastic', 'Plastic'), ('e-waste', 'E-Waste'), ('bulk', 'Bulk Waste')], default='mixed', max_length=20),
        ),
    ]
