# Generated by Django 5.2.7 on 2025-12-13 13:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0005_collectionrecord_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid by client at collection', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collection_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('on_demand', 'On-Demand')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('bank', 'Bank Transfer'), ('later', 'Invoice Later')], default='later', help_text='Payment method indicated by collector', max_length=20),
        ),
    ]
