# Generated by Django 5.2.7 on 2025-12-12 18:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_client_location'),
        ('collector', '0004_alter_collector_first_name_alter_collector_last_name'),
        ('waste_management_company', '0006_remove_company_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time_slot', models.CharField(max_length=50)),
                ('recurrence', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('area_zone', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('waste_type', models.CharField(choices=[('household', 'Household'), ('organic', 'Organic'), ('mixed', 'Mixed'), ('recyclable', 'Recyclable'), ('hazardous', 'Hazardous'), ('sanitary', 'Sanitary'), ('bulk', 'Bulk'), ('construction', 'Construction'), ('ewaste', 'E-Waste')], max_length=50)),
                ('bin_size_liters', models.PositiveIntegerField(choices=[(30, '30L Bin'), (60, '60L Bin'), (120, '120L Bin'), (240, '240L Bin'), (360, '360L Bin'), (660, '660L Bin'), (1100, '1100L Bin')])),
                ('bag_count', models.PositiveIntegerField(default=0)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_requests', to='client.client')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_requests', to='collector.collector')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_requests', to='waste_management_company.company')),
            ],
            options={
                'ordering': ['pickup_date', 'pickup_time_slot'],
            },
        ),
    ]
