# Generated by Django 5.2.7 on 2025-12-07 10:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_supervisor_user_delete_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
