# Generated by Django 5.2.7 on 2025-12-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='area_zone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='preferred_collection_time',
        ),
        migrations.RemoveField(
            model_name='client',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subscription_plan',
        ),
    ]
