# Generated by Django 5.2.7 on 2025-12-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='actual_start',
        ),
    ]
