# Generated by Django 5.2.7 on 2025-12-07 08:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_remove_routestop_actual_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default="0101000020E6100000D18EC0C4C48BCCBFFDEABB6C85621640", srid=4326),
            preserve_default=False,
        ),
    ]
