# Generated by Django 5.2.7 on 2025-12-07 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_routestop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
