# Generated by Django 5.2.7 on 2025-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_routestop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
