# Generated by Django 5.2.7 on 2025-12-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_location'),
        ('routes', '0007_routestop_actual_end_routestop_actual_start'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together=set(),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE routes_route
            ALTER COLUMN estimated_duration
            TYPE interval
            USING (estimated_duration * interval '1 second')
            """
        ),
        migrations.AlterField(
            model_name='route',
            name='estimated_duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'order'), name='unique_stop_order_per_route'),
        ),
    ]
