# Generated by Django 5.2.7 on 2025-12-09 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_routestop_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
