# Generated by Django 5.2.7 on 2025-12-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_demand', '0001_initial'),
        ('routes', '0009_alter_route_estimated_duration'),
        ('scheduled_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='client',
        ),
        migrations.AddField(
            model_name='routestop',
            name='ondemand_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stops', to='on_demand.ondemandrequest'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='scheduled_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stops', to='scheduled_request.scheduledrequest'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(help_text='1 means first stop in route'),
        ),
    ]
