# Generated by Django 5.2.7 on 2025-11-27 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=100)),
                ('registered_address', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=17)),
                ('contact_email', models.EmailField(max_length=254)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('weighing_system', models.CharField(max_length=50)),
                ('incentive_per_100_percent_route', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complaint_resolution_sla', models.IntegerField(help_text='SLA in hours')),
                ('total_producers', models.IntegerField(default=0)),
                ('total_collectors', models.IntegerField(default=0)),
                ('operational_cities', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
