# Generated by Django 5.2.7 on 2025-11-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management_company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_id',
        ),
    ]
