# Generated by Django 5.2.7 on 2025-11-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management_company', '0002_remove_company_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='registered_address',
        ),
    ]
