# Generated by Django 5.2.7 on 2025-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management_company', '0003_remove_company_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='incentive_per_100_percent_route',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
