# Generated by Django 5.2.7 on 2025-12-04 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management_company', '0004_alter_company_incentive_per_100_percent_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='closing_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='opening_time',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='working_days',
            field=models.JSONField(default=list),
        ),
    ]
