# Generated by Django 5.2.7 on 2025-12-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management_company', '0005_company_closing_time_company_opening_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
    ]
