# Generated by Django 5.2.7 on 2025-12-11 03:45

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_client_location'),
        ('collector', '0004_alter_collector_first_name_alter_collector_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('pickup_time_slot', models.CharField(choices=[('morning', 'Morning (6 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)')], max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('area_zone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='GIS point (lon, lat)', null=True, srid=4326)),
                ('bag_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bin_size_liters', models.IntegerField(blank=True, choices=[(120, '120L'), (240, '240L'), (360, '360L'), (660, '660L'), (1100, '1100L')], null=True)),
                ('waste_type', models.CharField(choices=[('wet', 'Organic Waste'), ('mixed', 'Mixed Waste'), ('recyclable', 'Recyclable Waste'), ('e_waste', 'E-Waste'), ('bulk', 'Bulk Waste'), ('sanitary', 'Sanitary/Biomedical Waste'), ('hazardous', 'Hazardous Household Waste'), ('construction', 'Construction & Demolition Waste'), ('household', 'General Household Waste')], max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('waste_image', models.ImageField(blank=True, help_text='Photo of the waste provided by client', null=True, upload_to='on_demand/waste_images/%Y/%m/%d/')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned to Collector'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_demand_requests', to='client.client')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_demand_requests', to='collector.collector')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['client', '-requested_at'], name='on_demand_o_client__7a446b_idx'), models.Index(fields=['collector', 'request_status'], name='on_demand_o_collect_e29332_idx'), models.Index(fields=['pickup_date', 'request_status'], name='on_demand_o_pickup__78f4d3_idx'), models.Index(fields=['area_zone', 'pickup_date'], name='on_demand_o_area_zo_146f38_idx')],
            },
        ),
    ]
