# Generated by Django 5.2.7 on 2025-11-30 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
        ('waste_management_company', '0003_remove_company_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_private_collector', models.BooleanField(default=False)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('assigned_area_zone', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('daily_wage_or_incentive_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account_details', models.TextField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_collections', models.IntegerField(default=0)),
                ('last_known_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_known_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='waste_management_company.company')),
            ],
        ),
    ]
