# Generated by Django 5.2.7 on 2025-12-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
        ('supervisor', '0004_alter_supervisor_company_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors_under_supervision', to='supervisor.supervisor'),
        ),
    ]
