# Generated by Django 5.2.7 on 2025-12-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_collector_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='first_name',
            field=models.CharField(default='Enext', max_length=100),
        ),
        migrations.AddField(
            model_name='collector',
            name='last_name',
            field=models.CharField(default='Kookyei', max_length=100),
        ),
    ]
