# Generated by Django 5.2.7 on 2025-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_collector_first_name_collector_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collector',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
