# Generated by Django 5.2.7 on 2025-12-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_alter_collector_first_name_alter_collector_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='employment_type',
        ),
    ]
