# Generated by Django 5.2.7 on 2025-11-30 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
        ('waste_management_company', '0003_remove_company_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('assigned_areas', models.JSONField(default=list)),
                ('team_size', models.IntegerField(default=0)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='waste_management_company.company')),
            ],
        ),
    ]
