# Generated by Django 5.2.7 on 2025-12-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
