# Generated by Django 5.2.7 on 2025-12-01 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_supervisor_first_name_supervisor_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='company',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='company_username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_supervisors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
