# Generated by Django 5.2.7 on 2025-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_remove_supervisor_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='company_username',
            field=models.CharField(max_length=150),
        ),
    ]
