# Generated by Django 5.2.7 on 2025-12-03 12:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste_management_company', '0004_alter_company_incentive_per_100_percent_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_code', models.CharField(help_text='Unique zone code (e.g., ACC-OSU-01)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Human-readable zone name (e.g., Osu Residential)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('zone_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use'), ('institutional', 'Institutional')], default='residential', max_length=20)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(help_text='Polygon defining zone boundaries (GeoJSON/WKT)', srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Center point of zone (auto-calculated if not provided)', null=True, srid=4326)),
                ('radius_meters', models.FloatField(blank=True, help_text='Radius in meters (for circular zones only)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('population_density', models.CharField(choices=[('low', 'Low (<50 people/hectare)'), ('medium', 'Medium (50-150 people/hectare)'), ('high', 'High (>150 people/hectare)')], default='medium', max_length=20)),
                ('estimated_households', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_fee_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for base service fees (1.0 = standard, 1.5 = 50% more)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('default_collection_days', models.JSONField(blank=True, default=list, help_text="Default collection days for this zone, e.g., ['monday', 'thursday']")),
                ('is_active', models.BooleanField(default=True, help_text='Whether zone is actively serviced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company that manages this zone', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='waste_management_company.company')),
                ('parent_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_zones', to='zones.zone')),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='zones_zone_company_8cecce_idx'), models.Index(fields=['city', 'zone_type'], name='zones_zone_city_0587b8_idx'), models.Index(fields=['zone_code'], name='zones_zone_zone_co_31e06d_idx')],
                'unique_together': {('company', 'zone_code')},
            },
        ),
    ]
