# Generated by Django 5.2.7 on 2025-12-03 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='zone',
            name='zones_zone_company_8cecce_idx',
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='default_collection_days',
            field=models.JSONField(blank=True, default=list, help_text="Default collection days (e.g. ['monday', 'thursday'])"),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the zone is actively serviced'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='service_fee_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for base service fees', max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['is_active'], name='zones_zone_is_acti_ca7736_idx'),
        ),
        migrations.RemoveField(
            model_name='zone',
            name='company',
        ),
    ]
