# Generated by Django 5.2.7 on 2025-12-07 08:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_remove_zone_zones_zone_company_8cecce_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='center_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Center point of zone (auto-calculated if not provided)', srid=4326),
        ),
    ]
